# Generated by Django 4.1.2 on 2023-02-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dyfiunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_bgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
                ('b_fathers_name', models.CharField(max_length=50)),
                ('b_age', models.CharField(max_length=2)),
                ('b_donated', models.DateField()),
                ('b_dyfi_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.dyfiunit')),
                ('b_gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.gender')),
                ('b_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.bloodgroup')),
            ],
        ),
        migrations.DeleteModel(
            name='Index_bg',
        ),
    ]
